name: DevSecOps

on:
    push:
        branches: [advanced]

jobs:

    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secret-scanning:
        uses: ./.github/workflows/secrete-scanning.yml

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    Dockerfile-Scan:
        uses: ./.github/workflows/docker-scan.yml
