# Goal - Ensure that docker file and images are tested for security vulnerabilities and misconfigurations.

name: Docker Scan

on:
  workflow_call:

jobs:
  docker-file-lint:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            include:
            - dockerfile-path: frontend/Dockerfile
              context: frontend
              image-name: frontend

            - dockerfile-path: backend/Dockerfile
              context: backend
              image-name: backend

    steps:

      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Dockerfile Linter
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.dockerfile-path }}

      - name: Docker Setup [Login]
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Secret
        run: |
            if [-z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
              echo "DockerHub token is missing"
              exit 1
            else 
              echo "DockerHub token is present"
            fi
      - name: Docker build
        run: |
           docker build \
           -t ${{ vars.DOCKERHUB_USERNAME }}/devboard-${{ matrix.image-name }}:latest \
           -f ${{ matrix.dockerfile-path }} \
            ${{ matrix.context }}
      

      
      
      - name: Run trivy scan on ${{ matrix.dockerfile-path }} image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/devboard-${{ matrix.dockerfile-path == 'frontend/Dockerfile' && 'frontend' || 'backend' }}:latest
          format: table
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          inherit-env: true